### ISSUE TITLE
Typo in `Bulb.js`

### ISSUE THREAD

**Issue by mstoetzer** [CliffS/ikea-tradfri#4]
Thanks for the lib!

You got a typo in [Bulb.js Line 33](https://github.com/CliffS/ikea-tradfri/blob/master/src/Bulb.coffee#L33):

`setBrighness` ;)

Sorry, don't have time for opening a PR.

Kind regards :)

**Comment by CliffS** [comment]
Thanks for the report.  Fixed in version 3.3.2.

Please let me know how you get on with the library.

**Comment by mstoetzer** [comment]
Yeah, I'm pretty happy with it. Good work!

I played a bit and created a small node-cli for myself: 
[https://github.com/bytekeks/tradfri-cli](https://github.com/bytekeks/tradfri-cli)

**Comment by CliffS** [comment]
Cute.  I may shamelessly steal your code and add a cli version to the library. :)

**Comment by mstoetzer** [comment]
Yes, do it ;)
