### ISSUE TITLE
Handling unknown devices

### ISSUE THREAD

**Issue by jwarby** [CliffS/ikea-tradfri#7]
Hi, I'm hitting an issue where the library is throwing an error because I've got a couple of dimmers, which seem to be missing from the underlying `node-tradfri-client` library.  The error is coming from here https://github.com/CliffS/ikea-tradfri/blob/master/src/Accessory.coffee#L22 after I call `.connect()`.

From what I can see there isn't a way for me to handle this error whilst still getting back the devices which are recognised, unless I'm missing something?

**Comment by CliffS** [comment]
I will look at this in the next day or two.  Sorry for the delay.

**Comment by jwarby** [comment]
No problem, thanks!

**Comment by CliffS** [comment]
Version 3.7.0 changes this behaviour.  If an unknown device type is encountered, the call to `@update` will return a generic `Accessory`. 

If you'd like to issue a PR for your dimmer, I'd appreciate that too.

**Comment by jwarby** [comment]
That's great, thanks for this!

I was originally just going to fix it and do a PR, but it looks like support for dimmers would need to be added to `node-tradfri-client` first?
